### ISSUE TITLE
Lost using your nice theme

### ISSUE THREAD

**Issue by blogdemoi** [ronv/minimalist#6]
Hi,

I am trying to use your nice theme. However I am a bit lost as I am used to follow the simple quick start guide at Hugo https://gohugo.io/getting-started/quick-start/ .

So I create a new site with:

```
hugo new site quickstart
cd quickstart
git init
git submodule add https://github.com/ronv/minimalist.git themes/minimalist
```
However I then have a config.toml in quickstart and a config.yaml in /quickstart/themes/minimalist/config.yaml.

Where should I begin then?

I have used Hugo for a few years but as a simple user to build my own blog and wish now to change my theme for yours but yours appear to be a  full project.

Thank you if you have time for any tips.

**Comment by ronv** [comment]
Hey! If you have installed Hugo on your machine then just download it and in root folder run "hugo server" to see it live on localhost. This theme is not created as submodule. It is ready site just remove sample posts and add your.

Br, Ronalds

**Comment by blogdemoi** [comment]
Thank you.
